version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-network

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - order-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      - POSTGRES_DB=inventorydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  shipping-db:
    image: postgres:15
    container_name: shipping-db
    environment:
      - POSTGRES_DB=shippingdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - shipping-db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  discovery-service:
    image: nishant165/discovery-service
    container_name: discovery-service
    networks:
      - ecommerce-network
    ports:
      - "8761:8761"

  config-server:
    image: nishant165/config-server
    container_name: config-server
    networks:
      - ecommerce-network
    depends_on:
      - discovery-service

  inventory-service:
    image: nishant165/inventory-service
    container_name: inventory-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - inventory-db

  order-service:
    image: nishant165/order-service
    container_name: order-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - order-db

  shipping-service:
    image: nishant165/shipping-service
    container_name: shipping-service
    networks:
      - ecommerce-network
    depends_on:
      - config-server
      - zipkin
      - shipping-db

  api-gateway:
    image: nishant165/api-gateway
    container_name: api-gateway
    networks:
      - ecommerce-network
    depends_on:
      - order-service
      - inventory-service
      - shipping-service
    ports:
      - "8080:8080"

volumes:
  order-db-data:
  inventory-db-data:
  shipping-db-data:

networks:
  ecommerce-network:
