#jwt:
#    secretKey: fkjdhkfsjlnrwlkntlrithrennlknlfnngfnsnflksnnfsdjn
spring:
  application:
    name: api-gateway
  config:
      import: configserver:http://config-server:8888
#
#  #api gateway config
#  cloud:
#    gateway:
#      routes:
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/orders/**
##            - Method= GET, POST
#          filters:
#            - StripPrefix=2
##            - RedirectTo=302, http://youtube.com
#            - name: LoggingOrdersFilter
#            - name: Authentication
#              args:
#                enabled: true
##            - name: Authoriation
##              args:
##                allowedRoles: ADMIN,SUPER_ADMIN
#        - id: inventory-service
#          uri: lb://INVENTORY-SERVICE
#          predicates:
#            - Path=/api/v1/inventory/**
#          filters:
#            - StripPrefix=2
#            - AddRequestHeader=X-Custom-Header, Nishant
#            - name: Authentication
#              args:
#                enabled: false
#        - id: shipping-service
#          uri: lb://SHIPPING-SERVICE
#          predicates:
#            - Path=/api/v1/shipping/**
#          filters:
#            - StripPrefix=2
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
