apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shipping-db
spec:
  selector:
    matchLabels:
      app: shipping-db
  serviceName: shipping-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-db
    spec:
      containers:
      - name: shipping-db
        image: postgres:16
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POSTGRES_USER
            value: "user"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "shippingdb"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard-rwo"
      volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-db-service
spec:
  clusterIP: None
  selector:
    app: shipping-db
  ports:
  - port: 5432
    targetPort: 5432
